import { contentSchema, type SiteContent } from "./schema";
const p = (name: string) => "/assets/photos/" + name + ".jpg";
export const defaultContent: SiteContent = contentSchema.parse({
  brand: {
    name: "Exotic Event & Entertainment",
    tagline: "People. Events. Emotions. Forever.",
    logo: "/assets/exotic/logos/logo-transparent-native.png",
    ribbon: "/assets/cinematic/gold-silk.webp",
    bookingLabel: "Book Your Event",
    phone: "+91 99096 15585",
    email: "",
    address: "S-41, Nilkanth Business Hub, Singanpor, Surat, Gujarat 395004",
    city: "Surat, Gujarat",
    maps: "https://maps.app.goo.gl/zBCxBvPwq22yLM7s8",
    whatsapp: "",
    instagram: "",
  },
  hero: {
    enabled: true,
    autoplay: true,
    intervalSeconds: 8,
    slides: [
      {
        eyebrow: "Ideas · People · Experiences",
        title: "Extraordinary\nevents for a",
        accent: "bigger tomorrow.",
        description:
          "Corporate gatherings, beautiful celebrations, and experiences that stay with you.",
        image: "/assets/cinematic/corporate.webp",
        alt: "Cinematic gold-lit ballroom with a keynote speaker and monumental ring chandeliers",
        label: "Corporate & beyond",
        cta: "Explore Experiences",
      },
      {
        eyebrow: "Dream · Plan · Decorate · Celebrate",
        title: "Extraordinary\nweddings.",
        accent: "Beautiful beginnings.",
        description:
          "Your story, brought to life through thoughtful planning and breathtaking décor.",
        image: "/assets/cinematic/wedding.webp",
        alt: "Cinematic Indian wedding setting with ivory flowers, crystal chandeliers and golden drapes",
        label: "Weddings & celebrations",
        cta: "Explore Weddings",
      },
      {
        eyebrow: "Destinations · Celebrations · Possibilities",
        title: "Different places.",
        accent: "The same forever.",
        description:
          "From an intimate lakeside evening to a grand destination celebration.",
        image: "/assets/cinematic/destination.webp",
        alt: "Cinematic lakeside palace terrace with a floral arch and candle lanterns at sunset",
        label: "Destination experiences",
        cta: "Discover Destinations",
      },
    ],
  },
  services: {
    enabled: true,
    eyebrow: "Our expertise",
    title: "Extraordinary.\nAt every scale.",
    description:
      "From the first idea to the final encore. We bring every detail together.",
    items: [
      {
        serviceSlug: "wedding-planning",
        title: "Weddings",
        description: "Your kind of forever.",
        image: p("hero-mandap-gold"),
        category: "01",
        alt: "Indian wedding beneath a golden chandelier",
      },
      {
        serviceSlug: "corporate-events",
        title: "Corporate events",
        description: "Make a lasting impression.",
        image: p("conference-stage"),
        category: "02",
        alt: "Speaker and conference audience",
      },
      {
        serviceSlug: "custom-decor",
        title: "Décor & styling",
        description: "Spaces with a point of view.",
        image: p("red-floral-dinner"),
        category: "03",
        alt: "Red floral arrangements and elegant dinner tables",
      },
      {
        serviceSlug: "destination-events",
        title: "Destinations",
        description: "Extraordinary, anywhere.",
        image: p("beach-ceremony"),
        category: "04",
        alt: "Beach ceremony with draped arch",
      },
      {
        serviceSlug: "navratri-events",
        title: "Celebrations",
        description: "Let the good times glow.",
        image: p("live-stage"),
        category: "05",
        alt: "Live performance with dramatic stage lighting",
      },
      {
        serviceSlug: "hospitality-management",
        title: "Hospitality",
        description: "Care in every detail.",
        image: p("ballroom-chandeliers"),
        category: "06",
        alt: "Grand ballroom prepared for guests",
      },
    ],
  },
  gallery: {
    enabled: true,
    eyebrow: "The world of Exotic",
    title: "Beautiful spaces.\nUnforgettable feelings.",
    description:
      "A closer look at the atmosphere, details, and celebrations we love.",
    items: [
      {
        keywords: "gold, mandap, floral, wedding, stage, decor, chandelier",
        featured: true,
        title: "A golden beginning",
        description: "Florals. Candlelight. Forever.",
        image: p("hero-mandap-gold"),
        category: "Weddings",
        alt: "Indian wedding ceremony beneath a gold chandelier",
      },
      {
        keywords: "corporate, ballroom, gala, chandeliers, reception, banquet",
        featured: true,
        title: "An evening, elevated",
        description: "A grand setting for a gathering.",
        image: p("ballroom-chandeliers"),
        category: "Corporate",
        alt: "Opulent ballroom with crystal chandeliers",
      },
      {
        keywords: "red, floral, flowers, table, dinner, candles, decor",
        featured: false,
        title: "Dinner, dressed in drama",
        description: "Every detail sets the mood.",
        image: p("red-floral-dinner"),
        category: "Décor",
        alt: "Red flowers and candles at a dinner reception",
      },
      {
        keywords: "stage, entertainment, concert, lighting, live, events",
        featured: false,
        title: "Feel it. Live it.",
        description: "The lights come up. The world falls away.",
        image: p("live-stage"),
        category: "Celebrations",
        alt: "Live concert crowd and illuminated stage",
      },
      {
        keywords: "beach, sea, destination, wedding, outdoor",
        featured: true,
        title: "Where the sea meets forever",
        description: "A new horizon for your story.",
        image: p("beach-ceremony"),
        category: "Destinations",
        alt: "White chairs at a beach wedding",
      },
      {
        keywords: "pink, floral, mandap, canopy, wedding, decor",
        featured: false,
        title: "Under a sky of flowers",
        description: "A beautiful place to begin.",
        image: p("wedding-mandap-ceremony"),
        category: "Weddings",
        alt: "Pink floral wedding canopy",
      },
      {
        keywords: "table, candlelight, green, dinner, reception, decor",
        featured: false,
        title: "The art of coming together",
        description: "Every place set. Every detail considered.",
        image: p("candlelit-reception"),
        category: "Décor",
        alt: "Candlelit tables with greenery",
      },
      {
        keywords: "garden, chandelier, green, lighting, outdoor, decor",
        featured: false,
        title: "A little after-dark magic",
        description: "Crystal light beneath a canopy of green.",
        image: p("chandelier-garden"),
        category: "Décor",
        alt: "Chandelier suspended among green foliage",
      },
      {
        keywords: "marigold, festive, navratri, garba, traditional, decor",
        featured: false,
        title: "Tradition, in full colour",
        description: "The things that bring us together.",
        image: p("festive-garlands"),
        category: "Celebrations",
        alt: "Marigold garlands and golden lotus ornaments",
      },
      {
        keywords: "birthday, balloons, pink, party, celebration",
        featured: false,
        title: "A reason to celebrate",
        description: "Make the milestone feel like you.",
        image: p("birthday-balloons"),
        category: "Celebrations",
        alt: "Pink balloon birthday celebration",
      },
    ],
  },
  feature: {
    enabled: true,
    eyebrow: "More than events",
    title: "We create\nworlds you can feel.",
    description:
      "The room. The energy. The little details. All coming together in one extraordinary moment.",
    image: p("ballroom-chandeliers"),
    alt: "Crystal chandeliers and luminous wedding reception tables",
    cta: "Create Your Moment",
  },
  process: {
    enabled: true,
    eyebrow: "The Exotic journey",
    title: "Your vision.\nOur full attention.",
    description:
      "One team. Every detail. From our first conversation to your last dance.",
    image: "/assets/cinematic/destination.webp",
    steps: [
      { title: "Discover", description: "Tell us your story." },
      { title: "Design", description: "Find the feeling." },
      { title: "Plan", description: "Bring it all together." },
      { title: "Create", description: "Watch it come alive." },
      { title: "Celebrate", description: "Be in the moment." },
    ],
  },
  faq: {
    enabled: true,
    eyebrow: "A few things to know",
    title: "Before the\nbeautiful begins.",
    items: [
      {
        question: "What kinds of events do you plan?",
        answer:
          "Weddings, corporate gatherings, festive occasions, destination events, and private celebrations — with décor and hospitality shaped around your occasion.",
      },
      {
        question: "Can we discuss décor only?",
        answer:
          "Yes. Tell us about your venue and the atmosphere you have in mind, and we can discuss the right décor and styling scope.",
      },
      {
        question: "Can you help with a destination event?",
        answer:
          "Share your preferred destination and dates. We will discuss venue, vendor, travel, and hospitality requirements with you.",
      },
      {
        question: "How do we get started?",
        answer:
          "Call us or send an enquiry with your occasion, date, city, and a few details. We will get in touch to talk through your plans.",
      },
    ],
  },
  contact: {
    enabled: true,
    eyebrow: "Let’s make it extraordinary",
    title: "Your next chapter.\nOur next masterpiece.",
    description: "A beautiful celebration begins with a conversation.",
    image: "/assets/cinematic/wedding.webp",
    cta: "Plan Your Celebration",
  },
  footer: {
    tagline: "Extraordinary events.\nLasting feelings.",
    imageryNote:
      "Cinematic brand imagery and selected stock photography. Event imagery is illustrative; ask us for our latest client portfolio.",
  },
});
